### PR TITLE
RFC: Feature/enhance node java initialization 91237294

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz What do you think of this so far? It doesn't yet have a pure promises API, which I've found is beyond my abilities today. But perhaps we should review what I have so far before I make further attempts at promises.

### CODE REVIEW

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
How keen are you to be able to use a pure promises API for registering clients before/after functions?

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
I would like to use the promisified version of the callback.  Are you thinking it will be hard to develop?

**Comment by jimlloyd** [comment]
PTAL at last commit. This PR is still an RFC until I have pure promises API for registering client before/after functions.

**Comment by jimlloyd** [comment]
Ok, I think this is now complete. PTAL, but I think I'd like to rebase and clean up a bit before we merge.

**Comment by mhfrantz** [comment]
FTP

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM - Rebase away!

**Comment by jimlloyd** [comment]
Replaced by #3.

**Pull request closed without merging**
